create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table public.registrations enable row level security;
grant insert on public.registrations to anon;
grant insert, select on public.registrations to authenticated;
drop policy if exists "Public can submit registrations" on public.registrations;
create policy "Public can submit registrations" on public.registrations for insert to anon with check (true);
drop policy if exists "Approved users can submit registrations" on public.registrations;
create policy "Approved users can submit registrations" on public.registrations for insert to authenticated with check (true);

create or replace view public.registered_members as
select id, name, photo_url, created_at from public.registrations;
revoke select on public.registered_members from anon;
grant select on public.registered_members to authenticated;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
grant select on public.admin_users to authenticated;
drop policy if exists "Admins can view their allowlist record" on public.admin_users;
create policy "Admins can view their allowlist record" on public.admin_users for select to authenticated using (user_id = auth.uid());

create table if not exists public.daily_performance (
  id bigint generated by default as identity primary key,
  member_key text not null,
  member_id text,
  member_name text not null,
  department_id text,
  department_name text,
  performance_date date not null,
  attendance boolean not null default false,
  daily_score numeric(5, 2) not null check (daily_score >= 0 and daily_score <= 100),
  remarks text,
  created_at timestamptz not null default now(),
  unique (member_key, performance_date)
);

alter table public.daily_performance add column if not exists member_id text;
alter table public.daily_performance add column if not exists department_id text;
alter table public.daily_performance add column if not exists department_name text;
alter table public.daily_performance add column if not exists remarks text;
alter table public.daily_performance enable row level security;
grant select on public.daily_performance to anon, authenticated;
grant insert, update, delete on public.daily_performance to authenticated;

drop policy if exists "Public can view daily performance" on public.daily_performance;
create policy "Public can view daily performance" on public.daily_performance for select to anon using (true);
drop policy if exists "Admins can view daily performance" on public.daily_performance;
create policy "Admins can view daily performance" on public.daily_performance for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));
drop policy if exists "Admins can insert daily performance" on public.daily_performance;
create policy "Admins can insert daily performance" on public.daily_performance for insert to authenticated with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
drop policy if exists "Admins can update daily performance" on public.daily_performance;
create policy "Admins can update daily performance" on public.daily_performance for update to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid())) with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
drop policy if exists "Admins can delete daily performance" on public.daily_performance;
create policy "Admins can delete daily performance" on public.daily_performance for delete to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));

insert into storage.buckets (id, name, public) values ('member-photos', 'member-photos', true) on conflict (id) do nothing;
drop policy if exists "Public can upload member photos" on storage.objects;
create policy "Authenticated users can upload member photos" on storage.objects for insert to authenticated with check (bucket_id = 'member-photos');
drop policy if exists "Public can view member photos" on storage.objects;
create policy "Authenticated users can view member photos" on storage.objects for select to authenticated using (bucket_id = 'member-photos');

-- Private portal profiles. Create the matching auth.users accounts in Supabase
-- Auth first, then insert one profile row for each approved member or admin.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  photo_url text,
  role text not null default 'member' check (role in ('member', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
grant select on public.profiles to authenticated;
grant update (name, photo_url) on public.profiles to authenticated;
create or replace function public.is_approved_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid())
    or exists (select 1 from public.admin_users where user_id = auth.uid())
$$;
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
    or exists (select 1 from public.admin_users where user_id = auth.uid())
$$;
create or replace view public.registered_members with (security_invoker = true) as
select id, name, photo_url, created_at from public.registrations;
drop policy if exists "Approved users can view registrations" on public.registrations;
create policy "Approved users can view registrations" on public.registrations
  for select to authenticated
  using (public.is_approved_user());
grant select on public.registered_members to authenticated;
drop policy if exists "Approved users can view profiles" on public.profiles;
create policy "Approved users can view profiles" on public.profiles
  for select to authenticated
  using (public.is_approved_user());
drop policy if exists "Members can update their profile" on public.profiles;
create policy "Members can update their profile" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());
drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles" on public.profiles
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Authenticated members may read performance; only admins may write it.
drop policy if exists "Public can view daily performance" on public.daily_performance;
drop policy if exists "Members can view daily performance" on public.daily_performance;
create policy "Members can view daily performance" on public.daily_performance
  for select to authenticated
  using (public.is_approved_user());
drop policy if exists "Admins can view daily performance" on public.daily_performance;
create policy "Admins can view daily performance" on public.daily_performance
  for select to authenticated
  using (public.is_admin());
drop policy if exists "Admins can insert daily performance" on public.daily_performance;
create policy "Admins can insert daily performance" on public.daily_performance
  for insert to authenticated
  with check (public.is_admin());
drop policy if exists "Admins can update daily performance" on public.daily_performance;
create policy "Admins can update daily performance" on public.daily_performance
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());
drop policy if exists "Admins can delete daily performance" on public.daily_performance;
create policy "Admins can delete daily performance" on public.daily_performance
  for delete to authenticated
  using (public.is_admin());

-- Private group chat. sender_id is always the authenticated user's id.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages (created_at desc);
alter table public.messages enable row level security;
grant select, insert on public.messages to authenticated;
grant delete on public.messages to authenticated;
drop policy if exists "Approved users can read messages" on public.messages;
create policy "Approved users can read messages" on public.messages
  for select to authenticated
  using (public.is_approved_user());
drop policy if exists "Approved users can send messages" on public.messages;
create policy "Approved users can send messages" on public.messages
  for insert to authenticated
  with check (sender_id = auth.uid() and public.is_approved_user());
drop policy if exists "Users can delete their own messages" on public.messages;
create policy "Users can delete their own messages" on public.messages
  for delete to authenticated
  using (sender_id = auth.uid());
drop policy if exists "Admins can delete messages" on public.messages;
create policy "Admins can delete messages" on public.messages
  for delete to authenticated
  using (public.is_admin());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
